// Auto-generated by deploy_site.py — do not edit manually
window.__REPORT_LIST__ = [
  {
    "date": "20260830",
    "label": "2026年08月30日",
    "file": "reports/CLS_早报_20260830.html"
  },
  {
    "date": "20260827",
    "label": "2026年08月27日",
    "file": "reports/CLS_早报_20260827.html"
  },
  {
    "date": "20260826",
    "label": "2026年08月26日",
    "file": "reports/CLS_早报_20260826.html"
  },
  {
    "date": "20260825",
    "label": "2026年08月25日",
    "file": "reports/CLS_早报_20260825.html"
  },
  {
    "date": "20260824",
    "label": "2026年08月24日",
    "file": "reports/CLS_早报_20260824.html"
  },
  {
    "date": "20260823",
    "label": "2026年08月23日",
    "file": "reports/CLS_早报_20260823.html"
  },
  {
    "date": "20260821",
    "label": "2026年08月21日",
    "file": "reports/CLS_早报_20260821.html"
  },
  {
    "date": "20260819",
    "label": "2026年08月19日",
    "file": "reports/CLS_早报_20260819.html"
  },
  {
    "date": "20260818",
    "label": "2026年08月18日",
    "file": "reports/CLS_早报_20260818.html"
  },
  {
    "date": "20260817",
    "label": "2026年08月17日",
    "file": "reports/CLS_早报_20260817.html"
  },
  {
    "date": "20260816",
    "label": "2026年08月16日",
    "file": "reports/CLS_早报_20260816.html"
  },
  {
    "date": "20260814",
    "label": "2026年08月14日",
    "file": "reports/CLS_早报_20260814.html"
  },
  {
    "date": "20260813",
    "label": "2026年08月13日",
    "file": "reports/CLS_早报_20260813.html"
  },
  {
    "date": "20260812",
    "label": "2026年08月12日",
    "file": "reports/CLS_早报_20260812.html"
  },
  {
    "date": "20260811",
    "label": "2026年08月11日",
    "file": "reports/CLS_早报_20260811.html"
  },
  {
    "date": "20260810",
    "label": "2026年08月10日",
    "file": "reports/CLS_早报_20260810.html"
  },
  {
    "date": "20260809",
    "label": "2026年08月09日",
    "file": "reports/CLS_早报_20260809.html"
  },
  {
    "date": "20260807",
    "label": "2026年08月07日",
    "file": "reports/CLS_早报_20260807.html"
  },
  {
    "date": "20260806",
    "label": "2026年08月06日",
    "file": "reports/CLS_早报_20260806.html"
  },
  {
    "date": "20260805",
    "label": "2026年08月05日",
    "file": "reports/CLS_早报_20260805.html"
  },
  {
    "date": "20260804",
    "label": "2026年08月04日",
    "file": "reports/CLS_早报_20260804.html"
  },
  {
    "date": "20260803",
    "label": "2026年08月03日",
    "file": "reports/CLS_早报_20260803.html"
  },
  {
    "date": "20260802",
    "label": "2026年08月02日",
    "file": "reports/CLS_早报_20260802.html"
  },
  {
    "date": "20260731",
    "label": "2026年07月31日",
    "file": "reports/CLS_早报_20260731.html"
  },
  {
    "date": "20260730",
    "label": "2026年07月30日",
    "file": "reports/CLS_早报_20260730.html"
  },
  {
    "date": "20260728",
    "label": "2026年07月28日",
    "file": "reports/CLS_早报_20260728.html"
  },
  {
    "date": "20260727",
    "label": "2026年07月27日",
    "file": "reports/CLS_早报_20260727.html"
  },
  {
    "date": "20260724",
    "label": "2026年07月24日",
    "file": "reports/CLS_早报_20260724.html"
  },
  {
    "date": "20260723",
    "label": "2026年07月23日",
    "file": "reports/CLS_早报_20260723.html"
  },
  {
    "date": "20260722",
    "label": "2026年07月22日",
    "file": "reports/CLS_早报_20260722.html"
  },
  {
    "date": "20260721",
    "label": "2026年07月21日",
    "file": "reports/CLS_早报_20260721.html"
  },
  {
    "date": "20260720",
    "label": "2026年07月20日",
    "file": "reports/CLS_早报_20260720.html"
  },
  {
    "date": "20260719",
    "label": "2026年07月19日",
    "file": "reports/CLS_早报_20260719.html"
  },
  {
    "date": "20260717",
    "label": "2026年07月17日",
    "file": "reports/CLS_早报_20260717.html"
  },
  {
    "date": "20260716",
    "label": "2026年07月16日",
    "file": "reports/CLS_早报_20260716.html"
  },
  {
    "date": "20260715",
    "label": "2026年07月15日",
    "file": "reports/CLS_早报_20260715.html"
  },
  {
    "date": "20260714",
    "label": "2026年07月14日",
    "file": "reports/CLS_早报_20260714.html"
  },
  {
    "date": "20260713",
    "label": "2026年07月13日",
    "file": "reports/CLS_早报_20260713.html"
  },
  {
    "date": "20260712",
    "label": "2026年07月12日",
    "file": "reports/CLS_早报_20260712.html"
  },
  {
    "date": "20260710",
    "label": "2026年07月10日",
    "file": "reports/CLS_早报_20260710.html"
  },
  {
    "date": "20260709",
    "label": "2026年07月09日",
    "file": "reports/CLS_早报_20260709.html"
  },
  {
    "date": "20260708",
    "label": "2026年07月08日",
    "file": "reports/CLS_早报_20260708.html"
  },
  {
    "date": "20260707",
    "label": "2026年07月07日",
    "file": "reports/CLS_早报_20260707.html"
  },
  {
    "date": "20260706",
    "label": "2026年07月06日",
    "file": "reports/CLS_早报_20260706.html"
  },
  {
    "date": "20260705",
    "label": "2026年07月05日",
    "file": "reports/CLS_早报_20260705.html"
  },
  {
    "date": "20260703",
    "label": "2026年07月03日",
    "file": "reports/CLS_早报_20260703.html"
  },
  {
    "date": "20260702",
    "label": "2026年07月02日",
    "file": "reports/CLS_早报_20260702.html"
  },
  {
    "date": "20260701",
    "label": "2026年07月01日",
    "file": "reports/CLS_早报_20260701.html"
  },
  {
    "date": "20260630",
    "label": "2026年06月30日",
    "file": "reports/CLS_早报_20260630.html"
  },
  {
    "date": "20260629",
    "label": "2026年06月29日",
    "file": "reports/CLS_早报_20260629.html"
  },
  {
    "date": "20260628",
    "label": "2026年06月28日",
    "file": "reports/CLS_早报_20260628.html"
  },
  {
    "date": "20260626",
    "label": "2026年06月26日",
    "file": "reports/CLS_早报_20260626.html"
  },
  {
    "date": "20260625",
    "label": "2026年06月25日",
    "file": "reports/CLS_早报_20260625.html"
  },
  {
    "date": "20260624",
    "label": "2026年06月24日",
    "file": "reports/CLS_早报_20260624.html"
  },
  {
    "date": "20260623",
    "label": "2026年06月23日",
    "file": "reports/CLS_早报_20260623.html"
  },
  {
    "date": "20260622",
    "label": "2026年06月22日",
    "file": "reports/CLS_早报_20260622.html"
  },
  {
    "date": "20260621",
    "label": "2026年06月21日",
    "file": "reports/CLS_早报_20260621.html"
  },
  {
    "date": "20260618",
    "label": "2026年06月18日",
    "file": "reports/CLS_早报_20260618.html"
  },
  {
    "date": "20260617",
    "label": "2026年06月17日",
    "file": "reports/CLS_早报_20260617.html"
  },
  {
    "date": "20260616",
    "label": "2026年06月16日",
    "file": "reports/CLS_早报_20260616.html"
  },
  {
    "date": "20260615",
    "label": "2026年06月15日",
    "file": "reports/CLS_早报_20260615.html"
  },
  {
    "date": "20260614",
    "label": "2026年06月14日",
    "file": "reports/CLS_早报_20260614.html"
  },
  {
    "date": "20260612",
    "label": "2026年06月12日",
    "file": "reports/CLS_早报_20260612.html"
  },
  {
    "date": "20260611",
    "label": "2026年06月11日",
    "file": "reports/CLS_早报_20260611.html"
  },
  {
    "date": "20260610",
    "label": "2026年06月10日",
    "file": "reports/CLS_早报_20260610.html"
  },
  {
    "date": "20260609",
    "label": "2026年06月09日",
    "file": "reports/CLS_早报_20260609.html"
  },
  {
    "date": "20260608",
    "label": "2026年06月08日",
    "file": "reports/CLS_早报_20260608.html"
  },
  {
    "date": "20260607",
    "label": "2026年06月07日",
    "file": "reports/CLS_早报_20260607.html"
  },
  {
    "date": "20260605",
    "label": "2026年06月05日",
    "file": "reports/CLS_早报_20260605.html"
  },
  {
    "date": "20260604",
    "label": "2026年06月04日",
    "file": "reports/CLS_早报_20260604.html"
  },
  {
    "date": "20260603",
    "label": "2026年06月03日",
    "file": "reports/CLS_早报_20260603.html"
  },
  {
    "date": "20260602",
    "label": "2026年06月02日",
    "file": "reports/CLS_早报_20260602.html"
  },
  {
    "date": "20260601",
    "label": "2026年06月01日",
    "file": "reports/CLS_早报_20260601.html"
  },
  {
    "date": "20260531",
    "label": "2026年05月31日",
    "file": "reports/CLS_早报_20260531.html"
  },
  {
    "date": "20260529",
    "label": "2026年05月29日",
    "file": "reports/CLS_早报_20260529.html"
  },
  {
    "date": "20260528",
    "label": "2026年05月28日",
    "file": "reports/CLS_早报_20260528.html"
  },
  {
    "date": "20260527",
    "label": "2026年05月27日",
    "file": "reports/CLS_早报_20260527.html"
  },
  {
    "date": "20260526",
    "label": "2026年05月26日",
    "file": "reports/CLS_早报_20260526.html"
  },
  {
    "date": "20260525",
    "label": "2026年05月25日",
    "file": "reports/CLS_早报_20260525.html"
  },
  {
    "date": "20260524",
    "label": "2026年05月24日",
    "file": "reports/CLS_早报_20260524.html"
  },
  {
    "date": "20260522",
    "label": "2026年05月22日",
    "file": "reports/CLS_早报_20260522.html"
  },
  {
    "date": "20260521",
    "label": "2026年05月21日",
    "file": "reports/CLS_早报_20260521.html"
  },
  {
    "date": "20260520",
    "label": "2026年05月20日",
    "file": "reports/CLS_早报_20260520.html"
  }
];
