// Auto-generated by deploy_site.py — do not edit manually
window.__REPORT_LIST__ = [
  {
    "date": "20260628",
    "label": "2026年06月28日",
    "file": "reports/CLS_早报_20260628.html"
  },
  {
    "date": "20260626",
    "label": "2026年06月26日",
    "file": "reports/CLS_早报_20260626.html"
  },
  {
    "date": "20260625",
    "label": "2026年06月25日",
    "file": "reports/CLS_早报_20260625.html"
  },
  {
    "date": "20260624",
    "label": "2026年06月24日",
    "file": "reports/CLS_早报_20260624.html"
  },
  {
    "date": "20260623",
    "label": "2026年06月23日",
    "file": "reports/CLS_早报_20260623.html"
  },
  {
    "date": "20260622",
    "label": "2026年06月22日",
    "file": "reports/CLS_早报_20260622.html"
  },
  {
    "date": "20260621",
    "label": "2026年06月21日",
    "file": "reports/CLS_早报_20260621.html"
  },
  {
    "date": "20260618",
    "label": "2026年06月18日",
    "file": "reports/CLS_早报_20260618.html"
  },
  {
    "date": "20260617",
    "label": "2026年06月17日",
    "file": "reports/CLS_早报_20260617.html"
  },
  {
    "date": "20260616",
    "label": "2026年06月16日",
    "file": "reports/CLS_早报_20260616.html"
  },
  {
    "date": "20260615",
    "label": "2026年06月15日",
    "file": "reports/CLS_早报_20260615.html"
  },
  {
    "date": "20260614",
    "label": "2026年06月14日",
    "file": "reports/CLS_早报_20260614.html"
  },
  {
    "date": "20260612",
    "label": "2026年06月12日",
    "file": "reports/CLS_早报_20260612.html"
  },
  {
    "date": "20260611",
    "label": "2026年06月11日",
    "file": "reports/CLS_早报_20260611.html"
  },
  {
    "date": "20260610",
    "label": "2026年06月10日",
    "file": "reports/CLS_早报_20260610.html"
  },
  {
    "date": "20260609",
    "label": "2026年06月09日",
    "file": "reports/CLS_早报_20260609.html"
  },
  {
    "date": "20260608",
    "label": "2026年06月08日",
    "file": "reports/CLS_早报_20260608.html"
  },
  {
    "date": "20260607",
    "label": "2026年06月07日",
    "file": "reports/CLS_早报_20260607.html"
  },
  {
    "date": "20260605",
    "label": "2026年06月05日",
    "file": "reports/CLS_早报_20260605.html"
  },
  {
    "date": "20260604",
    "label": "2026年06月04日",
    "file": "reports/CLS_早报_20260604.html"
  },
  {
    "date": "20260603",
    "label": "2026年06月03日",
    "file": "reports/CLS_早报_20260603.html"
  },
  {
    "date": "20260602",
    "label": "2026年06月02日",
    "file": "reports/CLS_早报_20260602.html"
  },
  {
    "date": "20260601",
    "label": "2026年06月01日",
    "file": "reports/CLS_早报_20260601.html"
  },
  {
    "date": "20260531",
    "label": "2026年05月31日",
    "file": "reports/CLS_早报_20260531.html"
  },
  {
    "date": "20260529",
    "label": "2026年05月29日",
    "file": "reports/CLS_早报_20260529.html"
  },
  {
    "date": "20260528",
    "label": "2026年05月28日",
    "file": "reports/CLS_早报_20260528.html"
  },
  {
    "date": "20260527",
    "label": "2026年05月27日",
    "file": "reports/CLS_早报_20260527.html"
  },
  {
    "date": "20260526",
    "label": "2026年05月26日",
    "file": "reports/CLS_早报_20260526.html"
  },
  {
    "date": "20260525",
    "label": "2026年05月25日",
    "file": "reports/CLS_早报_20260525.html"
  },
  {
    "date": "20260524",
    "label": "2026年05月24日",
    "file": "reports/CLS_早报_20260524.html"
  },
  {
    "date": "20260522",
    "label": "2026年05月22日",
    "file": "reports/CLS_早报_20260522.html"
  },
  {
    "date": "20260521",
    "label": "2026年05月21日",
    "file": "reports/CLS_早报_20260521.html"
  },
  {
    "date": "20260520",
    "label": "2026年05月20日",
    "file": "reports/CLS_早报_20260520.html"
  }
];
